apiVersion: v1
kind: Service
metadata:
  name: {{ include "webhull.fullname" . }}
  labels:
    {{- include "webhull.labels" . | nindent 4 }}
  {{- if .Values.monitoring.blackboxProbe.enabled }}
  annotations:
    monitoring.layer87.de/blackbox-probe: "true"
    monitoring.layer87.de/blackbox-target: {{ .Values.monitoring.blackboxProbe.target | default (printf "https://%s" .Values.gateway.host) | quote }}
    monitoring.layer87.de/blackbox-module: {{ .Values.monitoring.blackboxProbe.module | default "http_2xx" | quote }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  {{- if .Values.metricsService.enabled }}
  - port: {{ .Values.metricsService.port }}
    targetPort: health
    protocol: TCP
    name: metrics
  {{- end }}
  selector:
    {{- include "webhull.selectorLabels" . | nindent 4 }}
